// Code generated by counterfeiter. DO NOT EDIT.
package utils

import (
	"sync"

	"github.com/inference-gateway/adk/server/utils"
	"github.com/inference-gateway/adk/types"
	"github.com/inference-gateway/sdk"
)

type FakeMessageConverter struct {
	ConvertFromSDKStub        func(sdk.Message) (*types.Message, error)
	convertFromSDKMutex       sync.RWMutex
	convertFromSDKArgsForCall []struct {
		arg1 sdk.Message
	}
	convertFromSDKReturns struct {
		result1 *types.Message
		result2 error
	}
	convertFromSDKReturnsOnCall map[int]struct {
		result1 *types.Message
		result2 error
	}
	ConvertToSDKStub        func([]types.Message) ([]sdk.Message, error)
	convertToSDKMutex       sync.RWMutex
	convertToSDKArgsForCall []struct {
		arg1 []types.Message
	}
	convertToSDKReturns struct {
		result1 []sdk.Message
		result2 error
	}
	convertToSDKReturnsOnCall map[int]struct {
		result1 []sdk.Message
		result2 error
	}
	ValidateMessagePartStub        func(types.Part) error
	validateMessagePartMutex       sync.RWMutex
	validateMessagePartArgsForCall []struct {
		arg1 types.Part
	}
	validateMessagePartReturns struct {
		result1 error
	}
	validateMessagePartReturnsOnCall map[int]struct {
		result1 error
	}
	invocations      map[string][][]interface{}
	invocationsMutex sync.RWMutex
}

func (fake *FakeMessageConverter) ConvertFromSDK(arg1 sdk.Message) (*types.Message, error) {
	fake.convertFromSDKMutex.Lock()
	ret, specificReturn := fake.convertFromSDKReturnsOnCall[len(fake.convertFromSDKArgsForCall)]
	fake.convertFromSDKArgsForCall = append(fake.convertFromSDKArgsForCall, struct {
		arg1 sdk.Message
	}{arg1})
	stub := fake.ConvertFromSDKStub
	fakeReturns := fake.convertFromSDKReturns
	fake.recordInvocation("ConvertFromSDK", []interface{}{arg1})
	fake.convertFromSDKMutex.Unlock()
	if stub != nil {
		return stub(arg1)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *FakeMessageConverter) ConvertFromSDKCallCount() int {
	fake.convertFromSDKMutex.RLock()
	defer fake.convertFromSDKMutex.RUnlock()
	return len(fake.convertFromSDKArgsForCall)
}

func (fake *FakeMessageConverter) ConvertFromSDKCalls(stub func(sdk.Message) (*types.Message, error)) {
	fake.convertFromSDKMutex.Lock()
	defer fake.convertFromSDKMutex.Unlock()
	fake.ConvertFromSDKStub = stub
}

func (fake *FakeMessageConverter) ConvertFromSDKArgsForCall(i int) sdk.Message {
	fake.convertFromSDKMutex.RLock()
	defer fake.convertFromSDKMutex.RUnlock()
	argsForCall := fake.convertFromSDKArgsForCall[i]
	return argsForCall.arg1
}

func (fake *FakeMessageConverter) ConvertFromSDKReturns(result1 *types.Message, result2 error) {
	fake.convertFromSDKMutex.Lock()
	defer fake.convertFromSDKMutex.Unlock()
	fake.ConvertFromSDKStub = nil
	fake.convertFromSDKReturns = struct {
		result1 *types.Message
		result2 error
	}{result1, result2}
}

func (fake *FakeMessageConverter) ConvertFromSDKReturnsOnCall(i int, result1 *types.Message, result2 error) {
	fake.convertFromSDKMutex.Lock()
	defer fake.convertFromSDKMutex.Unlock()
	fake.ConvertFromSDKStub = nil
	if fake.convertFromSDKReturnsOnCall == nil {
		fake.convertFromSDKReturnsOnCall = make(map[int]struct {
			result1 *types.Message
			result2 error
		})
	}
	fake.convertFromSDKReturnsOnCall[i] = struct {
		result1 *types.Message
		result2 error
	}{result1, result2}
}

func (fake *FakeMessageConverter) ConvertToSDK(arg1 []types.Message) ([]sdk.Message, error) {
	var arg1Copy []types.Message
	if arg1 != nil {
		arg1Copy = make([]types.Message, len(arg1))
		copy(arg1Copy, arg1)
	}
	fake.convertToSDKMutex.Lock()
	ret, specificReturn := fake.convertToSDKReturnsOnCall[len(fake.convertToSDKArgsForCall)]
	fake.convertToSDKArgsForCall = append(fake.convertToSDKArgsForCall, struct {
		arg1 []types.Message
	}{arg1Copy})
	stub := fake.ConvertToSDKStub
	fakeReturns := fake.convertToSDKReturns
	fake.recordInvocation("ConvertToSDK", []interface{}{arg1Copy})
	fake.convertToSDKMutex.Unlock()
	if stub != nil {
		return stub(arg1)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *FakeMessageConverter) ConvertToSDKCallCount() int {
	fake.convertToSDKMutex.RLock()
	defer fake.convertToSDKMutex.RUnlock()
	return len(fake.convertToSDKArgsForCall)
}

func (fake *FakeMessageConverter) ConvertToSDKCalls(stub func([]types.Message) ([]sdk.Message, error)) {
	fake.convertToSDKMutex.Lock()
	defer fake.convertToSDKMutex.Unlock()
	fake.ConvertToSDKStub = stub
}

func (fake *FakeMessageConverter) ConvertToSDKArgsForCall(i int) []types.Message {
	fake.convertToSDKMutex.RLock()
	defer fake.convertToSDKMutex.RUnlock()
	argsForCall := fake.convertToSDKArgsForCall[i]
	return argsForCall.arg1
}

func (fake *FakeMessageConverter) ConvertToSDKReturns(result1 []sdk.Message, result2 error) {
	fake.convertToSDKMutex.Lock()
	defer fake.convertToSDKMutex.Unlock()
	fake.ConvertToSDKStub = nil
	fake.convertToSDKReturns = struct {
		result1 []sdk.Message
		result2 error
	}{result1, result2}
}

func (fake *FakeMessageConverter) ConvertToSDKReturnsOnCall(i int, result1 []sdk.Message, result2 error) {
	fake.convertToSDKMutex.Lock()
	defer fake.convertToSDKMutex.Unlock()
	fake.ConvertToSDKStub = nil
	if fake.convertToSDKReturnsOnCall == nil {
		fake.convertToSDKReturnsOnCall = make(map[int]struct {
			result1 []sdk.Message
			result2 error
		})
	}
	fake.convertToSDKReturnsOnCall[i] = struct {
		result1 []sdk.Message
		result2 error
	}{result1, result2}
}

func (fake *FakeMessageConverter) ValidateMessagePart(arg1 types.Part) error {
	fake.validateMessagePartMutex.Lock()
	ret, specificReturn := fake.validateMessagePartReturnsOnCall[len(fake.validateMessagePartArgsForCall)]
	fake.validateMessagePartArgsForCall = append(fake.validateMessagePartArgsForCall, struct {
		arg1 types.Part
	}{arg1})
	stub := fake.ValidateMessagePartStub
	fakeReturns := fake.validateMessagePartReturns
	fake.recordInvocation("ValidateMessagePart", []interface{}{arg1})
	fake.validateMessagePartMutex.Unlock()
	if stub != nil {
		return stub(arg1)
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *FakeMessageConverter) ValidateMessagePartCallCount() int {
	fake.validateMessagePartMutex.RLock()
	defer fake.validateMessagePartMutex.RUnlock()
	return len(fake.validateMessagePartArgsForCall)
}

func (fake *FakeMessageConverter) ValidateMessagePartCalls(stub func(types.Part) error) {
	fake.validateMessagePartMutex.Lock()
	defer fake.validateMessagePartMutex.Unlock()
	fake.ValidateMessagePartStub = stub
}

func (fake *FakeMessageConverter) ValidateMessagePartArgsForCall(i int) types.Part {
	fake.validateMessagePartMutex.RLock()
	defer fake.validateMessagePartMutex.RUnlock()
	argsForCall := fake.validateMessagePartArgsForCall[i]
	return argsForCall.arg1
}

func (fake *FakeMessageConverter) ValidateMessagePartReturns(result1 error) {
	fake.validateMessagePartMutex.Lock()
	defer fake.validateMessagePartMutex.Unlock()
	fake.ValidateMessagePartStub = nil
	fake.validateMessagePartReturns = struct {
		result1 error
	}{result1}
}

func (fake *FakeMessageConverter) ValidateMessagePartReturnsOnCall(i int, result1 error) {
	fake.validateMessagePartMutex.Lock()
	defer fake.validateMessagePartMutex.Unlock()
	fake.ValidateMessagePartStub = nil
	if fake.validateMessagePartReturnsOnCall == nil {
		fake.validateMessagePartReturnsOnCall = make(map[int]struct {
			result1 error
		})
	}
	fake.validateMessagePartReturnsOnCall[i] = struct {
		result1 error
	}{result1}
}

func (fake *FakeMessageConverter) Invocations() map[string][][]interface{} {
	fake.invocationsMutex.RLock()
	defer fake.invocationsMutex.RUnlock()
	fake.convertFromSDKMutex.RLock()
	defer fake.convertFromSDKMutex.RUnlock()
	fake.convertToSDKMutex.RLock()
	defer fake.convertToSDKMutex.RUnlock()
	fake.validateMessagePartMutex.RLock()
	defer fake.validateMessagePartMutex.RUnlock()
	copiedInvocations := map[string][][]interface{}{}
	for key, value := range fake.invocations {
		copiedInvocations[key] = value
	}
	return copiedInvocations
}

func (fake *FakeMessageConverter) recordInvocation(key string, args []interface{}) {
	fake.invocationsMutex.Lock()
	defer fake.invocationsMutex.Unlock()
	if fake.invocations == nil {
		fake.invocations = map[string][][]interface{}{}
	}
	if fake.invocations[key] == nil {
		fake.invocations[key] = [][]interface{}{}
	}
	fake.invocations[key] = append(fake.invocations[key], args)
}

var _ utils.MessageConverter = new(FakeMessageConverter)
