// Code generated by counterfeiter. DO NOT EDIT.
package mocks

import (
	"context"
	"sync"

	"github.com/inference-gateway/adk/server"
)

type FakeTool struct {
	ExecuteStub        func(context.Context, map[string]any) (string, error)
	executeMutex       sync.RWMutex
	executeArgsForCall []struct {
		arg1 context.Context
		arg2 map[string]any
	}
	executeReturns struct {
		result1 string
		result2 error
	}
	executeReturnsOnCall map[int]struct {
		result1 string
		result2 error
	}
	GetDescriptionStub        func() string
	getDescriptionMutex       sync.RWMutex
	getDescriptionArgsForCall []struct {
	}
	getDescriptionReturns struct {
		result1 string
	}
	getDescriptionReturnsOnCall map[int]struct {
		result1 string
	}
	GetNameStub        func() string
	getNameMutex       sync.RWMutex
	getNameArgsForCall []struct {
	}
	getNameReturns struct {
		result1 string
	}
	getNameReturnsOnCall map[int]struct {
		result1 string
	}
	GetParametersStub        func() map[string]any
	getParametersMutex       sync.RWMutex
	getParametersArgsForCall []struct {
	}
	getParametersReturns struct {
		result1 map[string]any
	}
	getParametersReturnsOnCall map[int]struct {
		result1 map[string]any
	}
	invocations      map[string][][]interface{}
	invocationsMutex sync.RWMutex
}

func (fake *FakeTool) Execute(arg1 context.Context, arg2 map[string]any) (string, error) {
	fake.executeMutex.Lock()
	ret, specificReturn := fake.executeReturnsOnCall[len(fake.executeArgsForCall)]
	fake.executeArgsForCall = append(fake.executeArgsForCall, struct {
		arg1 context.Context
		arg2 map[string]any
	}{arg1, arg2})
	stub := fake.ExecuteStub
	fakeReturns := fake.executeReturns
	fake.recordInvocation("Execute", []interface{}{arg1, arg2})
	fake.executeMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *FakeTool) ExecuteCallCount() int {
	fake.executeMutex.RLock()
	defer fake.executeMutex.RUnlock()
	return len(fake.executeArgsForCall)
}

func (fake *FakeTool) ExecuteCalls(stub func(context.Context, map[string]any) (string, error)) {
	fake.executeMutex.Lock()
	defer fake.executeMutex.Unlock()
	fake.ExecuteStub = stub
}

func (fake *FakeTool) ExecuteArgsForCall(i int) (context.Context, map[string]any) {
	fake.executeMutex.RLock()
	defer fake.executeMutex.RUnlock()
	argsForCall := fake.executeArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2
}

func (fake *FakeTool) ExecuteReturns(result1 string, result2 error) {
	fake.executeMutex.Lock()
	defer fake.executeMutex.Unlock()
	fake.ExecuteStub = nil
	fake.executeReturns = struct {
		result1 string
		result2 error
	}{result1, result2}
}

func (fake *FakeTool) ExecuteReturnsOnCall(i int, result1 string, result2 error) {
	fake.executeMutex.Lock()
	defer fake.executeMutex.Unlock()
	fake.ExecuteStub = nil
	if fake.executeReturnsOnCall == nil {
		fake.executeReturnsOnCall = make(map[int]struct {
			result1 string
			result2 error
		})
	}
	fake.executeReturnsOnCall[i] = struct {
		result1 string
		result2 error
	}{result1, result2}
}

func (fake *FakeTool) GetDescription() string {
	fake.getDescriptionMutex.Lock()
	ret, specificReturn := fake.getDescriptionReturnsOnCall[len(fake.getDescriptionArgsForCall)]
	fake.getDescriptionArgsForCall = append(fake.getDescriptionArgsForCall, struct {
	}{})
	stub := fake.GetDescriptionStub
	fakeReturns := fake.getDescriptionReturns
	fake.recordInvocation("GetDescription", []interface{}{})
	fake.getDescriptionMutex.Unlock()
	if stub != nil {
		return stub()
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *FakeTool) GetDescriptionCallCount() int {
	fake.getDescriptionMutex.RLock()
	defer fake.getDescriptionMutex.RUnlock()
	return len(fake.getDescriptionArgsForCall)
}

func (fake *FakeTool) GetDescriptionCalls(stub func() string) {
	fake.getDescriptionMutex.Lock()
	defer fake.getDescriptionMutex.Unlock()
	fake.GetDescriptionStub = stub
}

func (fake *FakeTool) GetDescriptionReturns(result1 string) {
	fake.getDescriptionMutex.Lock()
	defer fake.getDescriptionMutex.Unlock()
	fake.GetDescriptionStub = nil
	fake.getDescriptionReturns = struct {
		result1 string
	}{result1}
}

func (fake *FakeTool) GetDescriptionReturnsOnCall(i int, result1 string) {
	fake.getDescriptionMutex.Lock()
	defer fake.getDescriptionMutex.Unlock()
	fake.GetDescriptionStub = nil
	if fake.getDescriptionReturnsOnCall == nil {
		fake.getDescriptionReturnsOnCall = make(map[int]struct {
			result1 string
		})
	}
	fake.getDescriptionReturnsOnCall[i] = struct {
		result1 string
	}{result1}
}

func (fake *FakeTool) GetName() string {
	fake.getNameMutex.Lock()
	ret, specificReturn := fake.getNameReturnsOnCall[len(fake.getNameArgsForCall)]
	fake.getNameArgsForCall = append(fake.getNameArgsForCall, struct {
	}{})
	stub := fake.GetNameStub
	fakeReturns := fake.getNameReturns
	fake.recordInvocation("GetName", []interface{}{})
	fake.getNameMutex.Unlock()
	if stub != nil {
		return stub()
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *FakeTool) GetNameCallCount() int {
	fake.getNameMutex.RLock()
	defer fake.getNameMutex.RUnlock()
	return len(fake.getNameArgsForCall)
}

func (fake *FakeTool) GetNameCalls(stub func() string) {
	fake.getNameMutex.Lock()
	defer fake.getNameMutex.Unlock()
	fake.GetNameStub = stub
}

func (fake *FakeTool) GetNameReturns(result1 string) {
	fake.getNameMutex.Lock()
	defer fake.getNameMutex.Unlock()
	fake.GetNameStub = nil
	fake.getNameReturns = struct {
		result1 string
	}{result1}
}

func (fake *FakeTool) GetNameReturnsOnCall(i int, result1 string) {
	fake.getNameMutex.Lock()
	defer fake.getNameMutex.Unlock()
	fake.GetNameStub = nil
	if fake.getNameReturnsOnCall == nil {
		fake.getNameReturnsOnCall = make(map[int]struct {
			result1 string
		})
	}
	fake.getNameReturnsOnCall[i] = struct {
		result1 string
	}{result1}
}

func (fake *FakeTool) GetParameters() map[string]any {
	fake.getParametersMutex.Lock()
	ret, specificReturn := fake.getParametersReturnsOnCall[len(fake.getParametersArgsForCall)]
	fake.getParametersArgsForCall = append(fake.getParametersArgsForCall, struct {
	}{})
	stub := fake.GetParametersStub
	fakeReturns := fake.getParametersReturns
	fake.recordInvocation("GetParameters", []interface{}{})
	fake.getParametersMutex.Unlock()
	if stub != nil {
		return stub()
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *FakeTool) GetParametersCallCount() int {
	fake.getParametersMutex.RLock()
	defer fake.getParametersMutex.RUnlock()
	return len(fake.getParametersArgsForCall)
}

func (fake *FakeTool) GetParametersCalls(stub func() map[string]any) {
	fake.getParametersMutex.Lock()
	defer fake.getParametersMutex.Unlock()
	fake.GetParametersStub = stub
}

func (fake *FakeTool) GetParametersReturns(result1 map[string]any) {
	fake.getParametersMutex.Lock()
	defer fake.getParametersMutex.Unlock()
	fake.GetParametersStub = nil
	fake.getParametersReturns = struct {
		result1 map[string]any
	}{result1}
}

func (fake *FakeTool) GetParametersReturnsOnCall(i int, result1 map[string]any) {
	fake.getParametersMutex.Lock()
	defer fake.getParametersMutex.Unlock()
	fake.GetParametersStub = nil
	if fake.getParametersReturnsOnCall == nil {
		fake.getParametersReturnsOnCall = make(map[int]struct {
			result1 map[string]any
		})
	}
	fake.getParametersReturnsOnCall[i] = struct {
		result1 map[string]any
	}{result1}
}

func (fake *FakeTool) Invocations() map[string][][]interface{} {
	fake.invocationsMutex.RLock()
	defer fake.invocationsMutex.RUnlock()
	fake.executeMutex.RLock()
	defer fake.executeMutex.RUnlock()
	fake.getDescriptionMutex.RLock()
	defer fake.getDescriptionMutex.RUnlock()
	fake.getNameMutex.RLock()
	defer fake.getNameMutex.RUnlock()
	fake.getParametersMutex.RLock()
	defer fake.getParametersMutex.RUnlock()
	copiedInvocations := map[string][][]interface{}{}
	for key, value := range fake.invocations {
		copiedInvocations[key] = value
	}
	return copiedInvocations
}

func (fake *FakeTool) recordInvocation(key string, args []interface{}) {
	fake.invocationsMutex.Lock()
	defer fake.invocationsMutex.Unlock()
	if fake.invocations == nil {
		fake.invocations = map[string][][]interface{}{}
	}
	if fake.invocations[key] == nil {
		fake.invocations[key] = [][]interface{}{}
	}
	fake.invocations[key] = append(fake.invocations[key], args)
}

var _ server.Tool = new(FakeTool)
